import type { CfgFieldDef, CfgSectionSpec } from '@/features/settings/cfg-section-types';

const RITUAL_ROW: CfgFieldDef[] = [
  { key: 'title', label: 'Название', kind: 'text' },
  { key: 'description', label: 'Описание', kind: 'textarea', hint: 'Показывается в карточке и внизу списка.' },
  { key: 'icon', label: 'Иконка (имя файла)', kind: 'text', placeholder: 'sun', hint: 'Имя SVG в public/icons (без расширения).' },
  { key: 'level', label: 'Порядок', kind: 'number', min: 0, hint: 'Меньшее число — выше в списке.' },
];

const VOW_FIELDS: CfgFieldDef[] = [
  { key: 'title', label: 'Название', kind: 'text' },
  { key: 'description', label: 'Описание', kind: 'textarea', hint: 'Текст под заголовком в списке.' },
  { key: 'icon', label: 'Иконка', kind: 'text', hint: 'Имя файла в public/icons.' },
  { key: 'level', label: 'Порядок', kind: 'number', min: 0, hint: 'Порядок сортировки в списке.' },
];

const TASK_FIELDS_RITUALS: CfgFieldDef[] = [
  { key: 'title', label: 'Название', kind: 'text' },
  {
    key: 'task_type',
    label: 'Тип задачи',
    kind: 'select',
    hint: 'Как задача отображается и отмечается на главной.',
    options: [
      { value: 'checkbox', label: 'Чекбокс' },
      { value: 'number', label: 'Число' },
      { value: 'ritual', label: 'Ритуал' },
      { value: 'nutrition', label: 'Питание' },
      { value: 'list', label: 'Список' },
    ],
  },
  { key: 'icon', label: 'Иконка', kind: 'text', hint: 'Имя файла в public/icons.' },
  { key: 'level', label: 'Порядок', kind: 'number', min: 0, hint: 'Порядок в категории на главной.', suffix: ' №' },
  {
    key: 'ritual_type',
    label: 'Вид ритуала',
    kind: 'select',
    hint: 'Только для типа «Ритуал»: привязка к утру / вечеру / дню.',
    options: [
      { value: 'sunrise', label: 'Утренний' },
      { value: 'sunset', label: 'Вечерний' },
      { value: 'sun', label: 'Дневной' },
    ],
  },
  {
    key: 'cfg_target_value',
    label: 'Цель (число)',
    kind: 'number',
    min: 0,
    hint: 'Для типа «Число»; единица подставляется из поля ниже.',
    suffixFromField: 'cfg_unit',
    suffixHint: 'ед. ↓',
  },
  {
    key: 'cfg_unit',
    label: 'Единица',
    kind: 'text',
    placeholder: 'шт',
    hint: 'Подпись к числовой цели.',
    suffix: ' · ед.',
    suffixHint: 'ед.',
  },
  {
    key: 'cfg_target_hours',
    label: 'Цель таймера (ч)',
    kind: 'number',
    min: 0,
    step: 0.5,
    hint: 'План в часах для таймера.',
    suffix: ' ч',
    suffixHint: 'часы',
  },
  {
    key: 'config',
    label: 'config (JSON для списка)',
    kind: 'textarea',
    placeholder: '{"items":[]}',
    hint: 'Служебное поле для типа «Список»; по умолчанию пустой список.',
  },
  { key: 'is_optional', label: 'Необязательная', kind: 'checkbox', hint: 'Не влияет на прогресс категории, если включено.' },
];

const TASK_FIELDS_TIMER: CfgFieldDef[] = [
  { key: 'title', label: 'Название', kind: 'text' },
  {
    key: 'task_type',
    label: 'Тип задачи',
    kind: 'select',
    hint: 'Режим отображения и учёта времени / галочек.',
    options: [
      { value: 'checkbox', label: 'Чекбокс' },
      { value: 'number', label: 'Число' },
      { value: 'timer', label: 'Таймер' },
      { value: 'nutrition', label: 'Питание' },
      { value: 'list', label: 'Список' },
    ],
  },
  { key: 'icon', label: 'Иконка', kind: 'text', hint: 'Имя файла в public/icons.' },
  { key: 'level', label: 'Порядок', kind: 'number', min: 0, suffix: ' №' },
  {
    key: 'cfg_target_value',
    label: 'Цель (число)',
    kind: 'number',
    min: 0,
    suffixFromField: 'cfg_unit',
    suffixHint: 'ед. ↓',
    hint: 'Числовая цель; единица — в поле ниже.',
  },
  { key: 'cfg_unit', label: 'Единица', kind: 'text', suffix: ' · ед.', suffixHint: 'ед.' },
  {
    key: 'cfg_target_hours',
    label: 'Цель таймера (ч)',
    kind: 'number',
    min: 0,
    step: 0.5,
    hint: 'Плановые часы для таймера.',
    suffix: ' ч',
    suffixHint: 'часы',
  },
  { key: 'config', label: 'config (JSON)', kind: 'textarea', hint: 'Служебное поле; по умолчанию пустой список для типа «Список».' },
  { key: 'is_optional', label: 'Необязательная', kind: 'checkbox', hint: 'Не учитывается в среднем прогрессе категории.' },
];

const ACCOUNT_FIELDS: CfgFieldDef[] = [
  { key: 'title', label: 'Название', kind: 'text', hint: 'Подпись счёта в списках и формах.' },
  {
    key: 'type',
    label: 'Тип',
    kind: 'select',
    hint: 'Накопительный счёт можно выделить для целей сбережения.',
    options: [
      { value: 'regular', label: 'Обычный' },
      { value: 'savings', label: 'Накопления' },
    ],
  },
  {
    key: 'home_visible',
    label: 'Показывать на главной',
    kind: 'checkbox',
    hint: 'На домашней странице может быть видно максимум 3 счета.',
  },
  { key: 'icon', label: 'Иконка', kind: 'text', hint: 'Имя SVG в public/icons.' },
  { key: 'color', label: 'Цвет', kind: 'color', hint: 'Акцент строки в финансовых списках.' },
  {
    key: 'balance',
    label: 'Баланс',
    kind: 'number',
    step: 0.01,
    hint: 'Текущее значение в валюте приложения.',
    suffix: ' вал.',
    suffixHint: 'валюта',
  },
  {
    key: 'target',
    label: 'Цель',
    kind: 'number',
    step: 0.01,
    hint: 'Опционально: плановая сумма на счёте.',
    suffix: ' вал.',
    suffixHint: 'валюта',
  },
  { key: 'level', label: 'Порядок', kind: 'number', min: 0, hint: 'Порядок в выпадающих списках счетов.' },
];

const INCOME_CAT_FIELDS: CfgFieldDef[] = [
  { key: 'title', label: 'Название', kind: 'text', hint: 'Название в форме дохода.' },
  { key: 'icon', label: 'Иконка', kind: 'text', hint: 'Имя файла в public/icons.' },
  { key: 'color', label: 'Цвет', kind: 'color', hint: 'Акцент категории в UI.' },
  { key: 'level', label: 'Порядок', kind: 'number', min: 0, hint: 'Сортировка в списке категорий.' },
];

const EXPENSE_CAT_FIELDS: CfgFieldDef[] = [
  { key: 'title', label: 'Название', kind: 'text', hint: 'Название в форме расхода.' },
  { key: 'icon', label: 'Иконка', kind: 'text', hint: 'Имя файла в public/icons.' },
  { key: 'color', label: 'Цвет', kind: 'color', hint: 'Акцент категории в UI.' },
  {
    key: 'type',
    label: 'Импульсивная покупка',
    kind: 'checkbox',
    hint: 'Включите, если категория относится к импульсивным тратам.',
  },
  { key: 'level', label: 'Порядок', kind: 'number', min: 0, hint: 'Сортировка в списке категорий расходов.' },
];

const LEISURE_FIELDS: CfgFieldDef[] = [
  { key: 'title', label: 'Название', kind: 'text' },
  {
    key: 'task_type',
    label: 'Тип',
    kind: 'select',
    hint: 'Как задача досуга отображается и учитывается.',
    options: [
      { value: 'checkbox', label: 'Чекбокс' },
      { value: 'number', label: 'Число' },
      { value: 'nutrition', label: 'Питание' },
      { value: 'timer', label: 'Таймер' },
      { value: 'list', label: 'Список' },
    ],
  },
  { key: 'icon', label: 'Иконка', kind: 'text', hint: 'Имя файла в public/icons.' },
  { key: 'color', label: 'Цвет', kind: 'color' },
  {
    key: 'cfg_target_value',
    label: 'Цель (число)',
    kind: 'number',
    min: 0,
    suffixFromField: 'cfg_unit',
    suffixHint: 'ед. ↓',
    hint: 'Число; единица задаётся полем ниже.',
  },
  { key: 'cfg_unit', label: 'Единица', kind: 'text', suffix: ' · ед.', suffixHint: 'ед.' },
  {
    key: 'cfg_target_hours',
    label: 'Цель таймера (ч)',
    kind: 'number',
    min: 0,
    step: 0.5,
    suffix: ' ч',
    suffixHint: 'часы',
    hint: 'План в часах.',
  },
  { key: 'is_optional', label: 'Необязательная', kind: 'checkbox', hint: 'Не влияет на общий прогресс блока досуга.' },
  { key: 'level', label: 'Порядок', kind: 'number', min: 0, suffix: ' №' },
];

const AMBIENT_FIELDS: CfgFieldDef[] = [
  { key: 'name', label: 'Название', kind: 'text' },
  { key: 'icon', label: 'Иконка', kind: 'text', hint: 'Имя файла в public/icons.' },
  { key: 'file_name', label: 'Файл музыки', kind: 'text', hint: 'Выбирается из списка файлов в автоматически определённой папке музыки.' },
];

const DIARY_CAT_FIELDS: CfgFieldDef[] = [
  {
    key: 'title',
    label: 'Название',
    kind: 'text',
    hint: 'Подпись в селекторе категории при записи в дневнике.',
  },
  {
    key: 'icon',
    label: 'Иконка',
    kind: 'text',
    placeholder: 'book',
    hint: 'Имя файла в public/icons без расширения (как у настроений).',
  },
  { key: 'level', label: 'Порядок', kind: 'number', min: 0, hint: 'Меньшее число — выше в списке.' },
];

const DIARY_MOOD_FIELDS: CfgFieldDef[] = [
  { key: 'level', label: 'Уровень', kind: 'number', min: 1, hint: 'Позиция на шкале от 1 до 5.' },
  { key: 'title', label: 'Название', kind: 'text', hint: 'Человекочитаемая подпись уровня настроения.' },
  { key: 'color', label: 'Цвет', kind: 'color', hint: 'Цвет уровня в статистике и UI дневника.' },
  { key: 'icon', label: 'Иконка', kind: 'text', hint: 'Имя файла в public/icons.' },
];

const NUTRITION_PRODUCT_FIELDS: CfgFieldDef[] = [
  {
    key: 'title',
    label: 'Название',
    kind: 'text',
    hint: 'Как продукт показывается при добавлении порции питания.',
  },
  {
    key: 'group',
    label: 'Группа',
    kind: 'select',
    hint: 'Класс продукта для группировки в справочнике.',
    options: [
      { value: 'proteins', label: 'Белки' },
      { value: 'fats', label: 'Жиры' },
      { value: 'carbs', label: 'Углеводы' },
    ],
  },
  {
    key: 'portion_weight',
    label: 'Вес порции (г)',
    kind: 'number',
    min: 1,
    hint: 'Базовая порция для быстрого ввода (часто 100 г).',
    suffix: ' г',
    suffixHint: 'г',
  },
  {
    key: 'calories_per_100g',
    label: 'Ккал / 100г',
    kind: 'number',
    min: 0,
    hint: 'Энергия на 100 г продукта.',
    suffix: ' ккал',
    suffixHint: 'ккал',
  },
  {
    key: 'proteins_per_100g',
    label: 'Белки / 100г',
    kind: 'number',
    min: 0,
    hint: 'Граммы белка на 100 г.',
    suffix: ' г',
    suffixHint: 'г',
  },
  {
    key: 'fats_per_100g',
    label: 'Жиры / 100г',
    kind: 'number',
    min: 0,
    hint: 'Граммы жира на 100 г.',
    suffix: ' г',
    suffixHint: 'г',
  },
  {
    key: 'carbs_per_100g',
    label: 'Углеводы / 100г',
    kind: 'number',
    min: 0,
    hint: 'Граммы углеводов на 100 г.',
    suffix: ' г',
    suffixHint: 'г',
  },
  { key: 'level', label: 'Порядок', kind: 'number', min: 0, hint: 'Сортировка внутри списка продуктов.' },
];

const NUTRITION_PRESET_FIELDS: CfgFieldDef[] = [
  { key: 'title', label: 'Название', kind: 'text' },
  { key: 'icon', label: 'Иконка', kind: 'text' },
  {
    key: 'products',
    label: 'Состав (JSON)',
    kind: 'textarea',
    placeholder: '[]',
    hint: 'Массив продуктов и порций: хранится в поле products в базе.',
  },
  { key: 'level', label: 'Порядок', kind: 'number', min: 0 },
];

export const CFG_SECTION_SPECS: Record<string, CfgSectionSpec> = {
  'rituals-morning': {
    sectionId: 'rituals-morning',
    table: 'cfg_rituals_morning',
    title: 'Утренние ритуалы',
    description: '',
    fields: RITUAL_ROW,
    rowTitleKeys: ['title', 'id'],
    sortBy: 'level',
    createExtra: { active: 1 },
  },
  'rituals-evening': {
    sectionId: 'rituals-evening',
    table: 'cfg_rituals_evening',
    title: 'Вечерние ритуалы',
    description: '',
    fields: RITUAL_ROW,
    rowTitleKeys: ['title', 'id'],
    sortBy: 'level',
    createExtra: { active: 1 },
  },
  'rituals-vows': {
    sectionId: 'rituals-vows',
    table: 'cfg_vows',
    title: 'Обеты',
    description: '',
    fields: VOW_FIELDS,
    rowTitleKeys: ['title', 'id'],
    sortBy: 'level',
  },
  'tasks-rituals': {
    sectionId: 'tasks-rituals',
    table: 'cfg_tasks',
    title: 'Задачи — практики',
    description: '',
    filter: { category_type: 'rituals' },
    fields: TASK_FIELDS_RITUALS,
    sortBy: 'level',
    hideFormKeys: ['config', 'is_optional'],
    createExtra: { is_optional: 0, config: '{"items":[]}' },
  },
  'tasks-time': {
    sectionId: 'tasks-time',
    table: 'cfg_tasks',
    title: 'Задачи — фокус',
    description: '',
    filter: { category_type: 'time' },
    fields: TASK_FIELDS_TIMER,
    sortBy: 'level',
    hideFormKeys: ['config', 'is_optional'],
    createExtra: { is_optional: 0, config: '{"items":[]}' },
  },
  'tasks-body': {
    sectionId: 'tasks-body',
    table: 'cfg_tasks',
    title: 'Задачи — здоровье',
    description: '',
    filter: { category_type: 'body' },
    fields: TASK_FIELDS_TIMER,
    sortBy: 'level',
    hideFormKeys: ['config', 'is_optional'],
    createExtra: { is_optional: 0, config: '{"items":[]}' },
  },
  'tasks-deps': {
    sectionId: 'tasks-deps',
    table: 'cfg_tasks',
    title: 'Задачи — пороки',
    description: '',
    filter: { category_type: 'deps' },
    fields: TASK_FIELDS_TIMER,
    sortBy: 'level',
    hideFormKeys: ['config', 'is_optional'],
    createExtra: { is_optional: 0, config: '{"items":[]}' },
  },
  'finance-accounts': {
    sectionId: 'finance-accounts',
    table: 'cfg_accounts',
    title: 'Счета',
    description: '',
    fields: ACCOUNT_FIELDS,
    rowTitleKeys: ['title', 'id'],
    sortBy: 'level',
    createExtra: { balance: 0, type: 'regular' },
  },
  'finance-income': {
    sectionId: 'finance-income',
    table: 'cfg_income_categories',
    title: 'Категории доходов',
    description: '',
    fields: INCOME_CAT_FIELDS,
    sortBy: 'level',
  },
  'finance-expense': {
    sectionId: 'finance-expense',
    table: 'cfg_expense_categories',
    title: 'Категории расходов',
    description: '',
    fields: EXPENSE_CAT_FIELDS,
    sortBy: 'level',
  },
  'leisure-filling': {
    sectionId: 'leisure-filling',
    table: 'cfg_leisure_tasks',
    title: 'Досуг — наполнение',
    description: '',
    filter: { leisure_type: 'filling' },
    fields: LEISURE_FIELDS,
    sortBy: 'level',
    hideFormKeys: ['is_optional'],
    createExtra: { is_optional: 0 },
  },
  'leisure-escape': {
    sectionId: 'leisure-escape',
    table: 'cfg_leisure_tasks',
    title: 'Досуг — эскапизм',
    description: '',
    filter: { leisure_type: 'escape' },
    fields: LEISURE_FIELDS,
    sortBy: 'level',
    hideFormKeys: ['is_optional'],
    createExtra: { is_optional: 0 },
  },
  'ambient-music': {
    sectionId: 'ambient-music',
    table: 'cfg_ambient_music',
    title: 'Фоновая музыка',
    description: '',
    fields: AMBIENT_FIELDS,
    rowTitleKeys: ['name', 'id'],
    sortBy: 'none',
    createExtra: {},
  },
  'diary-categories': {
    sectionId: 'diary-categories',
    table: 'cfg_diary_categories',
    title: 'Категории дневника',
    description: '',
    fields: DIARY_CAT_FIELDS,
    sortBy: 'level',
    createExtra: { level: 0 },
  },
  'diary-moods': {
    sectionId: 'diary-moods',
    table: 'cfg_diary_moods',
    title: 'Настроения дневника',
    description: '',
    fields: DIARY_MOOD_FIELDS,
    sortBy: 'level',
    createExtra: { level: 3 },
  },
  'nutrition-products': {
    sectionId: 'nutrition-products',
    table: 'cfg_nutrition_products',
    title: 'Продукты питания',
    description: '',
    fields: NUTRITION_PRODUCT_FIELDS,
    rowTitleKeys: ['title', 'id'],
    sortBy: 'title',
    createExtra: {
      portion_weight: 100,
      calories_per_100g: 0,
      proteins_per_100g: 0,
      fats_per_100g: 0,
      carbs_per_100g: 0,
      group: 'proteins',
    },
  },
  'nutrition-presets': {
    sectionId: 'nutrition-presets',
    table: 'cfg_nutrition_presets',
    title: 'Блюда (пресеты)',
    description: '',
    fields: NUTRITION_PRESET_FIELDS,
    sortBy: 'title',
    createExtra: { products: '[]', usage_count: 0 },
  },
};

export function getCfgSectionSpec(sectionId: string): CfgSectionSpec | undefined {
  return CFG_SECTION_SPECS[sectionId];
}
