import type { CfgFieldDef, CfgSectionSpec } from '@/features/settings/cfg-section-types';

const RITUAL_ROW: CfgFieldDef[] = [
  { key: 'title', label: 'settings_cfg:fields.title.label', kind: 'text' },
  { key: 'description', label: 'settings_cfg:fields.description.label', kind: 'textarea', hint: 'settings_cfg:fields.description.hint' },
  { key: 'icon', label: 'settings_cfg:fields.icon.label', kind: 'text', placeholder: 'sun', hint: 'settings_cfg:fields.icon.hint' },
  { key: 'level', label: 'settings_cfg:fields.level.label', kind: 'number', min: 0, hint: 'settings_cfg:fields.level.hint' },
];

const VOW_FIELDS: CfgFieldDef[] = [
  { key: 'title', label: 'settings_cfg:fields.title.label', kind: 'text' },
  { key: 'description', label: 'settings_cfg:fields.description.label', kind: 'textarea', hint: 'settings_cfg:fields.description.hint' },
  { key: 'icon', label: 'settings_cfg:fields.icon.label', kind: 'text', hint: 'settings_cfg:fields.icon.hint' },
  { key: 'level', label: 'settings_cfg:fields.level.label', kind: 'number', min: 0, hint: 'settings_cfg:fields.level.hint' },
];

const TASK_FIELDS_RITUALS: CfgFieldDef[] = [
  { key: 'title', label: 'settings_cfg:fields.title.label', kind: 'text' },
  {
    key: 'task_type',
    label: 'settings_cfg:fields.task_type.label',
    kind: 'select',
    hint: 'settings_cfg:fields.task_type.hint',
    options: [
      { value: 'checkbox', label: 'settings_cfg:options.task_type.checkbox' },
      { value: 'number', label: 'settings_cfg:options.task_type.number' },
      { value: 'ritual', label: 'settings_cfg:options.task_type.ritual' },
      { value: 'nutrition', label: 'settings_cfg:options.task_type.nutrition' },
      { value: 'list', label: 'settings_cfg:options.task_type.list' },
    ],
  },
  { key: 'icon', label: 'settings_cfg:fields.icon.label', kind: 'text', hint: 'settings_cfg:fields.icon.hint' },
  { key: 'level', label: 'settings_cfg:fields.level.label', kind: 'number', min: 0, hint: 'settings_cfg:fields.level.hint', suffix: ' settings_cfg:units.num' },
  {
    key: 'ritual_type',
    label: 'settings_cfg:fields.ritual_type.label',
    kind: 'select',
    hint: 'settings_cfg:fields.ritual_type.hint',
    options: [
      { value: 'sunrise', label: 'settings_cfg:options.ritual_type.sunrise' },
      { value: 'sunset', label: 'settings_cfg:options.ritual_type.sunset' },
      { value: 'sun', label: 'settings_cfg:options.ritual_type.sun' },
    ],
  },
  {
    key: 'cfg_target_value',
    label: 'settings_cfg:fields.cfg_target_value.label',
    kind: 'number',
    min: 0,
    hint: 'settings_cfg:fields.cfg_target_value.hint',
    suffixFromField: 'cfg_unit',
    suffixHint: 'ед. ↓',
  },
  {
    key: 'cfg_unit',
    label: 'settings_cfg:fields.cfg_unit.label',
    kind: 'text',
    placeholder: 'шт',
    hint: 'settings_cfg:fields.cfg_unit.hint',
    suffix: ' · ед.',
    suffixHint: 'ед.',
  },
  {
    key: 'cfg_target_hours',
    label: 'settings_cfg:fields.cfg_target_hours.label',
    kind: 'number',
    min: 0,
    step: 0.5,
    hint: 'settings_cfg:fields.cfg_target_hours.hint',
    suffix: ' settings_cfg:units.hours',
    suffixHint: 'часы',
  },
  {
    key: 'config',
    label: 'settings_cfg:fields.config.label',
    kind: 'textarea',
    placeholder: '{"items":[]}',
    hint: 'settings_cfg:fields.config.hint',
  },
  { key: 'is_optional', label: 'settings_cfg:fields.is_optional.label', kind: 'checkbox', hint: 'settings_cfg:fields.is_optional.hint' },
];

const TASK_FIELDS_TIMER: CfgFieldDef[] = [
  { key: 'title', label: 'settings_cfg:fields.title.label', kind: 'text' },
  {
    key: 'task_type',
    label: 'settings_cfg:fields.task_type.label',
    kind: 'select',
    hint: 'settings_cfg:fields.task_type.hint',
    options: [
      { value: 'checkbox', label: 'settings_cfg:options.task_type.checkbox' },
      { value: 'number', label: 'settings_cfg:options.task_type.number' },
      { value: 'timer', label: 'settings_cfg:options.task_type.timer' },
      { value: 'nutrition', label: 'settings_cfg:options.task_type.nutrition' },
      { value: 'list', label: 'settings_cfg:options.task_type.list' },
    ],
  },
  { key: 'icon', label: 'settings_cfg:fields.icon.label', kind: 'text', hint: 'settings_cfg:fields.icon.hint' },
  { key: 'level', label: 'settings_cfg:fields.level.label', kind: 'number', min: 0, suffix: ' settings_cfg:units.num' },
  {
    key: 'cfg_target_value',
    label: 'settings_cfg:fields.cfg_target_value.label',
    kind: 'number',
    min: 0,
    suffixFromField: 'cfg_unit',
    suffixHint: 'ед. ↓',
    hint: 'settings_cfg:fields.cfg_target_value.hint',
  },
  { key: 'cfg_unit', label: 'settings_cfg:fields.cfg_unit.label', kind: 'text', suffix: ' · ед.', suffixHint: 'ед.' },
  {
    key: 'cfg_target_hours',
    label: 'settings_cfg:fields.cfg_target_hours.label',
    kind: 'number',
    min: 0,
    step: 0.5,
    hint: 'settings_cfg:fields.cfg_target_hours.hint',
    suffix: ' settings_cfg:units.hours',
    suffixHint: 'часы',
  },
  { key: 'config', label: 'settings_cfg:fields.config.label', kind: 'textarea', hint: 'settings_cfg:fields.config.hint' },
  { key: 'is_optional', label: 'settings_cfg:fields.is_optional.label', kind: 'checkbox', hint: 'settings_cfg:fields.is_optional.hint' },
];

const ACCOUNT_FIELDS: CfgFieldDef[] = [
  { key: 'title', label: 'settings_cfg:fields.title.label', kind: 'text', hint: 'settings_cfg:fields.title.hint' },
  {
    key: 'type',
    label: 'settings_cfg:fields.type.label',
    kind: 'select',
    hint: 'settings_cfg:fields.type.hint',
    options: [
      { value: 'regular', label: 'settings_cfg:options.account_type.regular' },
      { value: 'savings', label: 'settings_cfg:options.account_type.savings' },
    ],
  },
  {
    key: 'home_visible',
    label: 'settings_cfg:fields.home_visible.label',
    kind: 'checkbox',
    hint: 'settings_cfg:fields.home_visible.hint',
  },
  { key: 'icon', label: 'settings_cfg:fields.icon.label', kind: 'text', hint: 'settings_cfg:fields.icon.hint' },
  { key: 'color', label: 'settings_cfg:fields.color.label', kind: 'color', hint: 'settings_cfg:fields.color.hint' },
  {
    key: 'balance',
    label: 'settings_cfg:fields.balance.label',
    kind: 'number',
    step: 0.01,
    hint: 'settings_cfg:fields.balance.hint',
    suffix: ' settings_cfg:units.currency',
    suffixHint: 'валюта',
  },
  {
    key: 'target',
    label: 'settings_cfg:fields.target.label',
    kind: 'number',
    step: 0.01,
    hint: 'settings_cfg:fields.target.hint',
    suffix: ' settings_cfg:units.currency',
    suffixHint: 'валюта',
  },
  { key: 'level', label: 'settings_cfg:fields.level.label', kind: 'number', min: 0, hint: 'settings_cfg:fields.level.hint' },
];

const INCOME_CAT_FIELDS: CfgFieldDef[] = [
  { key: 'title', label: 'settings_cfg:fields.title.label', kind: 'text', hint: 'settings_cfg:fields.title.hint' },
  { key: 'icon', label: 'settings_cfg:fields.icon.label', kind: 'text', hint: 'settings_cfg:fields.icon.hint' },
  { key: 'color', label: 'settings_cfg:fields.color.label', kind: 'color', hint: 'settings_cfg:fields.color.hint' },
  { key: 'level', label: 'settings_cfg:fields.level.label', kind: 'number', min: 0, hint: 'settings_cfg:fields.level.hint' },
];

const EXPENSE_CAT_FIELDS: CfgFieldDef[] = [
  { key: 'title', label: 'settings_cfg:fields.title.label', kind: 'text', hint: 'settings_cfg:fields.title.hint' },
  { key: 'icon', label: 'settings_cfg:fields.icon.label', kind: 'text', hint: 'settings_cfg:fields.icon.hint' },
  { key: 'color', label: 'settings_cfg:fields.color.label', kind: 'color', hint: 'settings_cfg:fields.color.hint' },
  {
    key: 'type',
    label: 'Импульсивная покупка',
    kind: 'checkbox',
    hint: 'Включите, если категория относится к импульсивным тратам.',
  },
  { key: 'level', label: 'settings_cfg:fields.level.label', kind: 'number', min: 0, hint: 'settings_cfg:fields.level.hint' },
];

const LEISURE_FIELDS: CfgFieldDef[] = [
  { key: 'title', label: 'settings_cfg:fields.title.label', kind: 'text' },
  {
    key: 'task_type',
    label: 'Тип',
    kind: 'select',
    hint: 'Как задача досуга отображается и учитывается.',
    options: [
      { value: 'checkbox', label: 'settings_cfg:options.leisure_type.checkbox' },
      { value: 'number', label: 'settings_cfg:options.leisure_type.number' },
      { value: 'nutrition', label: 'settings_cfg:options.leisure_type.nutrition' },
      { value: 'timer', label: 'settings_cfg:options.leisure_type.timer' },
      { value: 'list', label: 'settings_cfg:options.leisure_type.list' },
    ],
  },
  { key: 'icon', label: 'settings_cfg:fields.icon.label', kind: 'text', hint: 'settings_cfg:fields.icon.hint' },
  { key: 'color', label: 'settings_cfg:fields.color.label', kind: 'color' },
  {
    key: 'cfg_target_value',
    label: 'settings_cfg:fields.cfg_target_value.label',
    kind: 'number',
    min: 0,
    suffixFromField: 'cfg_unit',
    suffixHint: 'ед. ↓',
    hint: 'settings_cfg:fields.cfg_target_value.hint',
  },
  { key: 'cfg_unit', label: 'settings_cfg:fields.cfg_unit.label', kind: 'text', suffix: ' · ед.', suffixHint: 'ед.' },
  {
    key: 'cfg_target_hours',
    label: 'settings_cfg:fields.cfg_target_hours.label',
    kind: 'number',
    min: 0,
    step: 0.5,
    suffix: ' settings_cfg:units.hours',
    suffixHint: 'часы',
    hint: 'settings_cfg:fields.cfg_target_hours.hint',
  },
  { key: 'is_optional', label: 'settings_cfg:fields.is_optional.label', kind: 'checkbox', hint: 'settings_cfg:fields.is_optional.hint' },
  { key: 'level', label: 'settings_cfg:fields.level.label', kind: 'number', min: 0, suffix: ' settings_cfg:units.num' },
];

const AMBIENT_FIELDS: CfgFieldDef[] = [
  { key: 'name', label: 'settings_cfg:fields.name.label', kind: 'text' },
  { key: 'icon', label: 'settings_cfg:fields.icon.label', kind: 'text', hint: 'settings_cfg:fields.icon.hint' },
  { key: 'file_name', label: 'settings_cfg:fields.file_name.label', kind: 'text', hint: 'settings_cfg:fields.file_name.hint' },
];

const DIARY_CAT_FIELDS: CfgFieldDef[] = [
  {
    key: 'title',
    label: 'settings_cfg:fields.title.label',
    kind: 'text',
    hint: 'settings_cfg:fields.title.hint',
  },
  {
    key: 'icon',
    label: 'settings_cfg:fields.icon.label',
    kind: 'text',
    placeholder: 'book',
    hint: 'settings_cfg:fields.icon.hint',
  },
  { key: 'level', label: 'settings_cfg:fields.level.label', kind: 'number', min: 0, hint: 'settings_cfg:fields.level.hint' },
];

const DIARY_MOOD_FIELDS: CfgFieldDef[] = [
  { key: 'level', label: 'Уровень', kind: 'number', min: 1, hint: 'Позиция на шкале от 1 до 5.' },
  { key: 'title', label: 'settings_cfg:fields.title.label', kind: 'text', hint: 'Человекочитаемая подпись уровня настроения.' },
  { key: 'color', label: 'settings_cfg:fields.color.label', kind: 'color', hint: 'Цвет уровня в статистике и UI дневника.' },
  { key: 'icon', label: 'settings_cfg:fields.icon.label', kind: 'text', hint: 'settings_cfg:fields.icon.hint' },
];

const DIARY_ENTRY_PRESET_FIELDS: CfgFieldDef[] = [
  {
    key: 'title',
    label: 'settings_cfg:fields.title.label',
    kind: 'text',
    hint: 'Короткая подпись для списка и поиска в настройках.',
  },
  {
    key: 'prompt',
    label: 'settings_cfg:fields.prompt.label',
    kind: 'textarea',
    hint: 'settings_cfg:fields.prompt.hint',
    placeholder: 'Например: Начни с одной честной строки.',
  },
  {
    key: 'description',
    label: 'settings_cfg:fields.description.label',
    kind: 'textarea',
    hint: 'Дополнительная заметка или пояснение к фразе.',
  },
  { key: 'icon', label: 'settings_cfg:fields.icon.label', kind: 'text', hint: 'settings_cfg:fields.icon.hint' },
  { key: 'active', label: 'settings_cfg:fields.active.label', kind: 'checkbox', hint: 'settings_cfg:fields.active.hint' },
  { key: 'level', label: 'settings_cfg:fields.level.label', kind: 'number', min: 0, hint: 'settings_cfg:fields.level.hint' },
];

const NUTRITION_PRODUCT_FIELDS: CfgFieldDef[] = [
  {
    key: 'title',
    label: 'settings_cfg:fields.title.label',
    kind: 'text',
    hint: 'Как продукт показывается при добавлении порции питания.',
  },
  {
    key: 'group',
    label: 'Группа',
    kind: 'select',
    hint: 'Класс продукта для группировки в справочнике.',
    options: [
      { value: 'proteins', label: 'settings_cfg:options.nutrition_group.proteins' },
      { value: 'fats', label: 'settings_cfg:options.nutrition_group.fats' },
      { value: 'carbs', label: 'settings_cfg:options.nutrition_group.carbs' },
    ],
  },
  {
    key: 'portion_weight',
    label: 'settings_cfg:fields.portion_weight.label',
    kind: 'number',
    min: 1,
    hint: 'settings_cfg:fields.portion_weight.hint',
    suffix: ' settings_cfg:units.grams',
    suffixHint: 'г',
  },
  {
    key: 'calories_per_100g',
    label: 'settings_cfg:fields.calories_per_100g.label',
    kind: 'number',
    min: 0,
    hint: 'settings_cfg:fields.calories_per_100g.hint',
    suffix: ' settings_cfg:units.calories',
    suffixHint: 'ккал',
  },
  {
    key: 'proteins_per_100g',
    label: 'settings_cfg:fields.proteins_per_100g.label',
    kind: 'number',
    min: 0,
    hint: 'settings_cfg:fields.proteins_per_100g.hint',
    suffix: ' settings_cfg:units.grams',
    suffixHint: 'г',
  },
  {
    key: 'fats_per_100g',
    label: 'settings_cfg:fields.fats_per_100g.label',
    kind: 'number',
    min: 0,
    hint: 'settings_cfg:fields.fats_per_100g.hint',
    suffix: ' settings_cfg:units.grams',
    suffixHint: 'г',
  },
  {
    key: 'carbs_per_100g',
    label: 'settings_cfg:fields.carbs_per_100g.label',
    kind: 'number',
    min: 0,
    hint: 'settings_cfg:fields.carbs_per_100g.hint',
    suffix: ' settings_cfg:units.grams',
    suffixHint: 'г',
  },
  { key: 'level', label: 'settings_cfg:fields.level.label', kind: 'number', min: 0, hint: 'settings_cfg:fields.level.hint' },
];

const NUTRITION_PRESET_FIELDS: CfgFieldDef[] = [
  { key: 'title', label: 'settings_cfg:fields.title.label', kind: 'text' },
  { key: 'icon', label: 'settings_cfg:fields.icon.label', kind: 'text' },
  {
    key: 'products',
    label: 'settings_cfg:fields.products.label',
    kind: 'textarea',
    placeholder: '[]',
    hint: 'settings_cfg:fields.products.hint',
  },
  { key: 'level', label: 'settings_cfg:fields.level.label', kind: 'number', min: 0 },
];

export const CFG_SECTION_SPECS: Record<string, CfgSectionSpec> = {
  'rituals-morning': {
    sectionId: 'rituals-morning',
    table: 'cfg_rituals_morning',
    title: 'settings_cfg:sections.rituals-morning.title',
    description: '',
    fields: RITUAL_ROW,
    rowTitleKeys: ['title', 'id'],
    sortBy: 'level',
    createExtra: { active: 1 },
  },
  'rituals-evening': {
    sectionId: 'rituals-evening',
    table: 'cfg_rituals_evening',
    title: 'settings_cfg:sections.rituals-evening.title',
    description: '',
    fields: RITUAL_ROW,
    rowTitleKeys: ['title', 'id'],
    sortBy: 'level',
    createExtra: { active: 1 },
  },
  'rituals-vows': {
    sectionId: 'rituals-vows',
    table: 'cfg_vows',
    title: 'settings_cfg:sections.rituals-vows.title',
    description: '',
    fields: VOW_FIELDS,
    rowTitleKeys: ['title', 'id'],
    sortBy: 'level',
  },
  'tasks-rituals': {
    sectionId: 'tasks-rituals',
    table: 'cfg_tasks',
    title: 'settings_cfg:sections.tasks-rituals.title',
    description: '',
    filter: { category_type: 'rituals' },
    fields: TASK_FIELDS_RITUALS,
    sortBy: 'level',
    hideFormKeys: ['config', 'is_optional'],
    createExtra: { is_optional: 0, config: '{"items":[]}' },
  },
  'tasks-time': {
    sectionId: 'tasks-time',
    table: 'cfg_tasks',
    title: 'settings_cfg:sections.tasks-time.title',
    description: '',
    filter: { category_type: 'time' },
    fields: TASK_FIELDS_TIMER,
    sortBy: 'level',
    hideFormKeys: ['config', 'is_optional'],
    createExtra: { is_optional: 0, config: '{"items":[]}' },
  },
  'tasks-body': {
    sectionId: 'tasks-body',
    table: 'cfg_tasks',
    title: 'settings_cfg:sections.tasks-body.title',
    description: '',
    filter: { category_type: 'body' },
    fields: TASK_FIELDS_TIMER,
    sortBy: 'level',
    hideFormKeys: ['config', 'is_optional'],
    createExtra: { is_optional: 0, config: '{"items":[]}' },
  },
  'tasks-deps': {
    sectionId: 'tasks-deps',
    table: 'cfg_tasks',
    title: 'settings_cfg:sections.tasks-deps.title',
    description: '',
    filter: { category_type: 'deps' },
    fields: TASK_FIELDS_TIMER,
    sortBy: 'level',
    hideFormKeys: ['config', 'is_optional'],
    createExtra: { is_optional: 0, config: '{"items":[]}' },
  },
  'finance-accounts': {
    sectionId: 'finance-accounts',
    table: 'cfg_accounts',
    title: 'settings_cfg:sections.finance-accounts.title',
    description: '',
    fields: ACCOUNT_FIELDS,
    rowTitleKeys: ['title', 'id'],
    sortBy: 'level',
    createExtra: { balance: 0, type: 'regular' },
  },
  'finance-income': {
    sectionId: 'finance-income',
    table: 'cfg_income_categories',
    title: 'settings_cfg:sections.finance-income.title',
    description: '',
    fields: INCOME_CAT_FIELDS,
    sortBy: 'level',
  },
  'finance-expense': {
    sectionId: 'finance-expense',
    table: 'cfg_expense_categories',
    title: 'settings_cfg:sections.finance-expense.title',
    description: '',
    fields: EXPENSE_CAT_FIELDS,
    sortBy: 'level',
  },
  'leisure-filling': {
    sectionId: 'leisure-filling',
    table: 'cfg_leisure_tasks',
    title: 'settings_cfg:sections.leisure-filling.title',
    description: '',
    filter: { leisure_type: 'filling' },
    fields: LEISURE_FIELDS,
    sortBy: 'level',
    hideFormKeys: ['is_optional'],
    createExtra: { is_optional: 0 },
  },
  'leisure-escape': {
    sectionId: 'leisure-escape',
    table: 'cfg_leisure_tasks',
    title: 'settings_cfg:sections.leisure-escape.title',
    description: '',
    filter: { leisure_type: 'escape' },
    fields: LEISURE_FIELDS,
    sortBy: 'level',
    hideFormKeys: ['is_optional'],
    createExtra: { is_optional: 0 },
  },
  'ambient-music': {
    sectionId: 'ambient-music',
    table: 'cfg_ambient_music',
    title: 'settings_cfg:sections.ambient-music.title',
    description: '',
    fields: AMBIENT_FIELDS,
    rowTitleKeys: ['name', 'id'],
    sortBy: 'none',
    createExtra: {},
  },
  'diary-categories': {
    sectionId: 'diary-categories',
    table: 'cfg_diary_categories',
    title: 'settings_cfg:sections.diary-categories.title',
    description: '',
    fields: DIARY_CAT_FIELDS,
    sortBy: 'level',
    createExtra: { level: 0 },
  },
  'diary-moods': {
    sectionId: 'diary-moods',
    table: 'cfg_diary_moods',
    title: 'settings_cfg:sections.diary-moods.title',
    description: '',
    fields: DIARY_MOOD_FIELDS,
    sortBy: 'level',
    createExtra: { level: 3 },
  },
  'diary-entry-presets': {
    sectionId: 'diary-entry-presets',
    table: 'cfg_diary_entry_presets',
    title: 'settings_cfg:sections.diary-entry-presets.title',
    description: '',
    fields: DIARY_ENTRY_PRESET_FIELDS,
    rowTitleKeys: ['title', 'prompt', 'id'],
    sortBy: 'level',
    createExtra: { active: 1, level: 0, title: 'Новая цитата', prompt: 'Например: начни с одной честной строки.' },
  },
  'nutrition-products': {
    sectionId: 'nutrition-products',
    table: 'cfg_nutrition_products',
    title: 'settings_cfg:sections.nutrition-products.title',
    description: '',
    fields: NUTRITION_PRODUCT_FIELDS,
    rowTitleKeys: ['title', 'id'],
    sortBy: 'title',
    createExtra: {
      portion_weight: 100,
      calories_per_100g: 0,
      proteins_per_100g: 0,
      fats_per_100g: 0,
      carbs_per_100g: 0,
      group: 'proteins',
    },
  },
  'nutrition-presets': {
    sectionId: 'nutrition-presets',
    table: 'cfg_nutrition_presets',
    title: 'settings_cfg:sections.nutrition-presets.title',
    description: '',
    fields: NUTRITION_PRESET_FIELDS,
    sortBy: 'title',
    createExtra: { products: '[]', usage_count: 0 },
  },
};

export function getCfgSectionSpec(sectionId: string): CfgSectionSpec | undefined {
  return CFG_SECTION_SPECS[sectionId];
}
